config/routes.rb
Enspiral::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get "login",  :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  root :to => 'accounts#index'

  get 'roladex' => 'profiles#roladex'
  get 'roladex/new_person' => 'company_memberships#new_person'
  get 'search' => 'search#index'
  match 'people/get_cities/:id' => 'people#get_cities'

  resources :profiles, only: [:edit, :update, :show, :index, :check_blog_fetches] do
  end

  resources :accounts do
    get 'public', on: :collection
    get 'closed', on: :collection
    get '/balances/(:limit)' => "accounts#balances", :as => :balances
    get 'transactions', on: :member
    post :reopen, on: :member
    resources :accounts_people
    resources :accounts_companies
  end

  resources :projects do
    get :edit_project_bookings
    put :update_project_bookings, on: :member
    resources :invoices do
      get :closed, on: :collection
      get :search, on: :collection
      get :imported, on: :collection
      post :close, on: :member
      post :reconcile, on: :member
      post :approve, on: :member
      post :reverse, on: :member
    end
  end

  get '/capacity' => 'project_bookings#index', :as => :capacity
  get '/capacity/person/:id' => 'project_bookings#person', :as => :person_capacity

  resources :your_capacity, only: :index do
    put :update, on: :collection
  end

  resources :project_memberships, :except => [:index, :edit, :show, :update] do
    put :update, on: :collection
  end

  resources :customers do
    post :approve, on: :member
    resources :invoices do
      get :closed, :on => :collection
      post :close, on: :member
      post :reconcile, on: :member
      post :approve, on: :member
      post :reverse, on: :member
      post :disburse, :on => :member
      post :pay_and_disburse, :on => :member
      get :imported, on: :collection
      get :search, on: :collection
    end
  end

  resources :companies do
    member do
      get 'xero_import_dashboard', as: 'xero_import_dashboard'
      get 'xero_import_single', as: 'xero_import_single'
      get 'xero_invoice_manual_check', as: 'xero_invoice_manual_check'
    end
    resources :accounts do
      collection do
        get 'public'
        get 'closed'
        get 'external'
        match 'historic_balances'
      end
      member do
        get 'transactions'
        post :reopen
      end
      get '/balances/(:limit)' => "accounts#balances", :as => :balances
      get '/history' => 'accounts#history', :as => :history
      get '/transfer' => 'accounts#transfer', :as => :transfer
      post '/do_transfer' => 'accounts#do_transfer', :as => :do_transfer
      resources :accounts_people
      resources :accounts_companies
    end

    resources :funds_transfers, only: [:create, :new, :index] do
      member do
        match 'undo'
      end
      collection do
        match 'external'
      end
    end
    resources :funds_transfer_templates do
      post :generate, on: :member
    end

    resources :customers do
      post :approve, on: :member, as: "approve_customer"
      get  :pending, :on => :collection
      resources :invoices do
        get :closed, :on => :collection
        get :imported, :on => :collection
        post :disburse, :on => :member
        post :reverse, :on => :member
        post :pay_and_disburse, :on => :member
        get :search, :on => :collection
      end
    end

    resources :projects do
      resources :invoices do
        get :closed, :on => :collection
        get :imported, :on => :collection
        post :disburse, :on => :member
        post :reverse, :on => :member
        post :pay_and_disburse, :on => :member
        get :search, :on => :collection
      end
    end

    resources :company_memberships, :path => :memberships do
      get :new_person, on: :collection
    end

    resources :reports do
      get :search, :on => :collection
      get :cash_position, :on => :collection
      get :contribution, :on => :collection
      get :manual_cash_position, :on => :collection
      get :top_customers, :on => :collection
    end

    resources :invoices do
      collection do
        get :projects
        get :closed
        get :search
        get :imported
      end
      post :close, on: :member
      post :reconcile, on: :member
      post :approve, on: :member
      post :reverse, on: :member
      resources :payments, only: [] do
        member do
          get :reverse
        end
      end
    end

    resources :metrics

    resources :external_accounts, only: [:index] do
    end
  end

  namespace :admin do
    resources :featured_items
    resources :companies do
      resources :company_memberships do
        get :new_person, on: :collection
      end
    end

    resources :groups
    resources :skills
    resources :service_categories
    resources :countries
    resources :cities


  end

  resources :external_accounts, only: [:index] do
    resources :external_transactions, only: [:index] do
    end
  end

  resources :external_transactions, only: [] do
    member do
      post :reconcile, action: :create_reconcilation
      get :reconcile, action: :reconcile
    end
  end

  match 'surveys' => 'surveys#index', as: :surveys
  match 'upload_survey' => 'surveys#upload_survey', as: :upload_surveys
  post '/upload_survey' => 'surveys#upload_survey', :as => :upload_surveys
  match 'survey_results/(:id)' => 'surveys#survey_results', as: :survey_results
  match 'take_survey' => 'surveys#survey', as: :take_survey
  match '/midtranet' => 'midtranet#index', as: :midtranet
 
  #match 'services' => 'services#index', :as => :services
  #match 'services/search' => 'services#search', :as => :services_search
  #namespace :staff do
  #
    #get '/' => 'dashboard#dashboard'
    #get '/dashboard' => 'dashboard#dashboard'

    #match '/capacity/edit' => 'project_bookings#edit', :via => :get, :as => :capacity_edit
    #match '/capacity/update' => 'project_bookings#update', :via => :put, :as => :capacity_update

    #match 'funds_transfer' => 'people#funds_transfer', :as => :funds_transfer

    #resources :customers
    #resources :services
    #resources :projects
    #resources :project_memberships, :except => [:index, :edit, :show, :update]
    #match '/project_memberships/update' => 'project_memberships#update', :via => :put, :as => :project_memberships_update

    #resources :accounts do
      #get '/balances/(:limit)' => "accounts#balances", :as => :balances
      #get '/history' => 'accounts#history', :as => :history
      #get '/transfer' => 'accounts#transfer', :as => :transfer
      #post '/do_transfer' => 'accounts#do_transfer', :as => :do_transfer
      #resources :account_permissions, :as => 'permissions'
    #end

    #namespace :reports do
      #resources :sales, :controller => :sales_report, :only => :index
    #end
  #end
end

app/views/notifier/alert_company_admins_of_failing_invoice_import.html.haml
%p
  Hi, admins for #{@company.name}!
%p
  The script couldn't import #{@invoices_with_errors.count} invoices (out of #{@total_invoice_count}) when importing invoices into #{@company.name}.
%p
  Details (also can be found on the
  = link_to "Imports Dashboard", xero_import_dashboard_company_url(@company)
  for your company):
%p
  %table
    - @invoices_with_errors.each do |invoice_ref, error_message|
      %tr
        %td
          Invoice ref #{invoice_ref}
          Error: #{error_message}
%p
  Cheers
%p
  my.enspiral bot

app/views/notifier/alert_funds_cleared_out.html.haml
%p
	Hi #{@person.first_name} !
%p
	One of more of your invoices has been paid and a total of NZD $ #{@amount} has been transfer to your my.enspiral account.
%p
	Thanks,
%p
	my.enspiral backend bot,

app/views/notifier/capacity_notification.html.haml
%h1 Project bookings reminder
%p Booking in how many hours you have allocated to projects per week allows us to see who has work and who does not.
%p We request that you visit #{link_to('Your Capacity', your_capacity_index_url)} and indicate how your workload looks for the next few months.
%p You may need to join or create a project before it will show up on this page.
%p= "While you are on the #{APP_CONFIG[:organization]} site.. it would be a good idea to ensure that your profile is up to date."
%p
  In other words:
  %br
  %i update these if you want to live.
  ="\- arnold schwarzenegger ( #{APP_CONFIG[:organization]} member since 1977, former governor of california)"

=link_to 'Update your project bookings', your_capacity_index_url

%table
  %thead
    %tr
      %th
        %strong Projects
      - week_dates(@start_on, @finish_on).each do |date|
        %th
          %strong= date.to_s

  %tbody
    - @person.project_memberships.each do |membership|
      -project = membership.project
      -bookings = membership.project_bookings
      %tr
        %td= link_to project.name, project
        - bookings.total_hours_per_week(@start_on, @finish_on).each do |week, hours|
          %td.centered= hours

app/views/notifier/contact.html.haml
Name: #{@options[:name]}
%br/
Email: #{@options[:email]}
%br/
Location: #{@options[:location]}
%br/
%p= @options[:enquiry]
%br/

app/views/notifier/contact.text.haml
Location: #{@options[:location]}

Name: #{@options[:name]}

Email: #{@options[:email]}

Enquiry: #{@options[:enquiry]}

app/views/notifier/mail_current_developers.html.haml
%p
  The my.enspiral script encountered a config error when trying to import invoices for #{@company.name}.
%p
  Details:
%p
  = @error.message
  = @error.backtrace
%p
  Cheers
%p
  my.enspiral bot

app/views/notifier/notify_user_of.html.haml
%h1= @notice.summary
%p= @notice.text
%p
  Posted by #{@notice.person.name}

app/views/notifier/notify_user_of.text.haml
= @notice.summary
= @notice.text
Posted by #{@notice.person.name}

app/views/notifier/send_welcome.html.haml
%h3
	Welcome #{@person.email} !
%p
	Please find enclosed your my.enspiral account details. Ensure that you change your password to something unique and secure when you first login
%p
	Email : #{@person.email}
%p
	Password : #{@password}