config/routes.rb
Enspiral::Application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get "login",  :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  root :to => 'accounts#index'

  get 'roladex' => 'profiles#roladex'
  get 'roladex/new_person' => 'company_memberships#new_person'
  get 'search' => 'search#index'
  match 'people/get_cities/:id' => 'people#get_cities'

  resources :profiles, only: [:edit, :update, :show, :index, :check_blog_fetches] do
  end

  resources :accounts do
    get 'public', on: :collection
    get 'closed', on: :collection
    get '/balances/(:limit)' => "accounts#balances", :as => :balances
    get 'transactions', on: :member
    post :reopen, on: :member
    resources :accounts_people
    resources :accounts_companies
  end

  resources :projects do
    get :edit_project_bookings
    put :update_project_bookings, on: :member
    resources :invoices do
      get :closed, on: :collection
      get :search, on: :collection
      get :imported, on: :collection
      post :close, on: :member
      post :reconcile, on: :member
      post :approve, on: :member
      post :reverse, on: :member
    end
  end

  get '/capacity' => 'project_bookings#index', :as => :capacity
  get '/capacity/person/:id' => 'project_bookings#person', :as => :person_capacity

  resources :your_capacity, only: :index do
    put :update, on: :collection
  end

  resources :project_memberships, :except => [:index, :edit, :show, :update] do
    put :update, on: :collection
  end

  resources :customers do
    post :approve, on: :member
    resources :invoices do
      get :closed, :on => :collection
      post :close, on: :member
      post :reconcile, on: :member
      post :approve, on: :member
      post :reverse, on: :member
      post :disburse, :on => :member
      post :pay_and_disburse, :on => :member
      get :imported, on: :collection
      get :search, on: :collection
    end
  end

  resources :companies do
    member do
      get 'xero_import_dashboard', as: 'xero_import_dashboard'
      get 'xero_import_single', as: 'xero_import_single'
      get 'xero_invoice_manual_check', as: 'xero_invoice_manual_check'
    end
    resources :accounts do
      collection do
        get 'public'
        get 'closed'
        get 'external'
        match 'historic_balances'
      end
      member do
        get 'transactions'
        post :reopen
      end
      get '/balances/(:limit)' => "accounts#balances", :as => :balances
      get '/history' => 'accounts#history', :as => :history
      get '/transfer' => 'accounts#transfer', :as => :transfer
      post '/do_transfer' => 'accounts#do_transfer', :as => :do_transfer
      resources :accounts_people
      resources :accounts_companies
    end

    resources :funds_transfers, only: [:create, :new, :index] do
      member do
        match 'undo'
      end
      collection do
        match 'external'
      end
    end
    resources :funds_transfer_templates do
      post :generate, on: :member
    end

    resources :customers do
      post :approve, on: :member, as: "approve_customer"
      get  :pending, :on => :collection
      resources :invoices do
        get :closed, :on => :collection
        get :imported, :on => :collection
        post :disburse, :on => :member
        post :reverse, :on => :member
        post :pay_and_disburse, :on => :member
        get :search, :on => :collection
      end
    end

    resources :projects do
      resources :invoices do
        get :closed, :on => :collection
        get :imported, :on => :collection
        post :disburse, :on => :member
        post :reverse, :on => :member
        post :pay_and_disburse, :on => :member
        get :search, :on => :collection
      end
    end

    resources :company_memberships, :path => :memberships do
      get :new_person, on: :collection
    end

    resources :reports do
      get :search, :on => :collection
      get :cash_position, :on => :collection
      get :contribution, :on => :collection
      get :manual_cash_position, :on => :collection
      get :top_customers, :on => :collection
    end

    resources :invoices do
      collection do
        get :projects
        get :closed
        get :search
        get :imported
      end
      post :close, on: :member
      post :reconcile, on: :member
      post :approve, on: :member
      post :reverse, on: :member
      resources :payments, only: [] do
        member do
          get :reverse
        end
      end
    end

    resources :metrics

    resources :external_accounts, only: [:index] do
    end
  end

  namespace :admin do
    resources :featured_items
    resources :companies do
      resources :company_memberships do
        get :new_person, on: :collection
      end
    end

    resources :groups
    resources :skills
    resources :service_categories
    resources :countries
    resources :cities


  end

  resources :external_accounts, only: [:index] do
    resources :external_transactions, only: [:index] do
    end
  end

  resources :external_transactions, only: [] do
    member do
      post :reconcile, action: :create_reconcilation
      get :reconcile, action: :reconcile
    end
  end

  match 'surveys' => 'surveys#index', as: :surveys
  match 'upload_survey' => 'surveys#upload_survey', as: :upload_surveys
  post '/upload_survey' => 'surveys#upload_survey', :as => :upload_surveys
  match 'survey_results/(:id)' => 'surveys#survey_results', as: :survey_results
  match 'take_survey' => 'surveys#survey', as: :take_survey
  match '/midtranet' => 'midtranet#index', as: :midtranet
 
  #match 'services' => 'services#index', :as => :services
  #match 'services/search' => 'services#search', :as => :services_search
  #namespace :staff do
  #
    #get '/' => 'dashboard#dashboard'
    #get '/dashboard' => 'dashboard#dashboard'

    #match '/capacity/edit' => 'project_bookings#edit', :via => :get, :as => :capacity_edit
    #match '/capacity/update' => 'project_bookings#update', :via => :put, :as => :capacity_update

    #match 'funds_transfer' => 'people#funds_transfer', :as => :funds_transfer

    #resources :customers
    #resources :services
    #resources :projects
    #resources :project_memberships, :except => [:index, :edit, :show, :update]
    #match '/project_memberships/update' => 'project_memberships#update', :via => :put, :as => :project_memberships_update

    #resources :accounts do
      #get '/balances/(:limit)' => "accounts#balances", :as => :balances
      #get '/history' => 'accounts#history', :as => :history
      #get '/transfer' => 'accounts#transfer', :as => :transfer
      #post '/do_transfer' => 'accounts#do_transfer', :as => :do_transfer
      #resources :account_permissions, :as => 'permissions'
    #end

    #namespace :reports do
      #resources :sales, :controller => :sales_report, :only => :index
    #end
  #end
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < AdminController
  def index
    @transactions = Transaction.transactions_with_totals(Transaction.order('date DESC, amount DESC'))
    @transactions.sort!{|a,b| b[0].date <=> a[0].date}
    @pending_total = sum_allocations(InvoiceAllocation.pending)
  end

  private

  def sum_allocations(allocations)
    allocations.inject(0) {|total, allocation| total += allocation.amount}
  end
end

app/views/admin/transactions/index.html.haml
%h1 Recent transactions

#graph{:style => "width:700px; height:250px;"}

- unless @transactions.empty?
  %table.transactions
    %tr
      %th Account
      %th Date
      %th Amount
      %th Description
      %th Running Total

    - @transactions.each do |transaction, sub_total|
      %tr.transaction{:style => "color:#{transaction.amount < 0 ? '#800' : '#060'};"}
        %td= link_to(transaction.account.name, admin_account_path(transaction.account))
        %td{:style => "width:70px;"}= transaction.date
        %td{:style => "width:55px;"}= transaction.amount
        %td= transaction.description
        %td{:style => "font-weight:bold; color:#{sub_total < 0 ? '#800' : '#060'};"}= number_to_currency(sub_total)

- content_for :javascripts do
  :javascript
    $(function () {
      var d1 = [
        #{@transactions.map { |t, st| '[' + (t.date.to_time.to_i*1000).to_s + ',' + st.to_s + '],' }}
      ];

      var d2 = [
        [#{@transactions.first[0].date.to_time.to_i*1000}, #{@pending_total}],
        [#{@transactions.last[0].date.to_time.to_i*1000}, #{@pending_total}],
      ];
      
      function plotWithOptions(t) {
        $.plot($("#graph"), [
          {
            data: d2,
            color: "rgb(200, 200, 200)",
            lines: { 
              show: true,
              fill: true
            },
            threshold: { 
              below: t, 
              color: "rgb(175, 175, 175)" 
            }
          },
          {
            data: d1,
            color: "rgb(0, 155, 0)",
            lines: { 
              show: true,
              fill: true
            },
            threshold: { 
              below: t, 
              color: "rgb(155, 0, 0)" 
            }
          }
        ],
        { 
          xaxis: { 
            mode: "time", 
            timeformat: "%y/%m/%d" 
          },
          yaxis: {
            tickFormatter: function (val, axis) { return "$" + (val/1000) + "k"; }
          }
        });
      }
   
      plotWithOptions(0);
    });